name: Build & Release Plugin

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Triggers when a version tag (e.g., v1.0.1) is pushed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Package Plugin
        run: npm run package

      - name: Upload Plugin ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: infinity-gallery
          path: dist/infinity-gallery.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.actor == 'LoganRickert' # Only you can trigger releases
  
    permissions:
      contents: write  # Restrict token to writing releases only
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: infinity-gallery
          path: dist/

      - name: Get Tag Message
        id: tag_message
        run: echo "message=$(git tag -n99 -l ${{ github.ref_name }} | sed 's/^.* //')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Infinity Gallery ${{ github.ref_name }}
          body: "${{ env.message || 'New release of Infinity Gallery 🎉' }}"
          draft: false
          prerelease: false
          files: dist/infinity-gallery.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
